{{ if .Values.resourceLimit }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service.name }}
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
{{ end }}